# Generated by Django 2.2.14 on 2022-06-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flames', '0002_reveal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
